spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:stock_random_rank;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8080
  error:
    whitelabel:
      enabled: false